# Always read coding conventions
read: CONVENTIONS.md

# AI guidelines plus extra project design and workflow files
file:
    - AI.md
    - SPECIFICATION.md
    - PLAN.md

# Automated testing
test-cmd: ./run_test_cycle.sh
auto-test: true
